config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :gads_auths
  resources :oauth2_tokens
  resources :oauth2_configs
  get '/', to: 'homes#index'
  root :to => "home#index"
  get "login/prompt", to: 'logins#prompt'
  get "login/callback", to: 'logins#callback'
  get "login/logout", to: 'logins#logout'
  get "login/", to: 'logins#index'

  get "login/prompt_ga", to: 'logins#prompt_ga'
  get "login/callback_ga", to: 'logins#callback_ga'
  get 'login/twitter', to: 'logins#twitter'

  get '/auth/:provider/callback', to: 'logins#twitter'
  get 'login/logout_twitter', to: 'logins#twitter_destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/homes_controller.rb
require 'rest-client'
class HomesController < ApplicationController
  def index
    @token_adwords = Oauth2Token.where(access_token: session[:token_adwords]["access_token"]).first if session[:token_adwords]
    @token_analytics = Oauth2Token.where(access_token: session[:token_analytics]["access_token"]).first if session[:token_analytics].present?
    @allToken = Oauth2Token.all.order(created_at: :DESC)
  end
end

app/views/homes/index.html.slim
p
  | Hello
- if flash[:alert]
  .alert
    = flash[:alert]
- if flash[:notice]
  .notice
    = flash[:notice]
= link_to 'logout Twitter', login_logout_twitter_path if params.present?
= link_to 'logout Google', login_logout_path if session[:token_adwords].present?
= link_to 'logout Google', login_logout_path if session[:token_analytics].present?
p
  = link_to 'Get token_adwords', login_prompt_path if session[:token_adwords].blank?
p
  = link_to 'Get token_analytics', login_prompt_ga_path if session[:token_analytics].blank?
p
  = link_to 'Get token_analytics', '/auth/twitter' if session[:token_twitter].blank?
- if @token_adwords.present?
  h1
    | Your token_adwords token:
  = @token_adwords.inspect if @token_adwords.present?

  p access_token
  textarea rows='2'
    = @token_adwords.try(:access_token)
  p refresh_token
  textarea rows='2'
    = @token_adwords.try(:refresh_token)
  hr
- if @token_analytics.present?
  h1
    | Your token_analytics token:
  = @token_analytics.inspect if @token_analytics.present?
  p access_token
  textarea rows='2'
    = @token_analytics.try(:access_token)
  p refresh_token
  textarea rows='2'
    = @token_analytics.try(:refresh_token)
- if params.present?
  h1
    | Your token_twitter token:
  p access_token
  textarea rows='2'
    = params[:token]
  p refresh_token
  textarea rows='2'
    = params[:secret]